tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1c1b1a",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#79301b",
        "background": "#fdf9f6",
        "tertiary-fixed-dim": "#d7c3b1",
        "on-tertiary-fixed-variant": "#524436",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "inverse-primary": "#c8c6c6",
        "surface-variant": "#e5e2df",
        "on-surface-variant": "#444748",
        "on-primary": "#ffffff",
        "surface-container-high": "#ebe7e4",
        "tertiary-container": "#372b1e",
        "secondary-fixed": "#ffdbd1",
        "surface-dim": "#ddd9d6",
        "tertiary-fixed": "#f4dfcc",
        "on-tertiary": "#ffffff",
        "surface-container": "#f1edea",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f4f0ed",
        "surface-container-low": "#f7f3f0",
        "primary-container": "#2d2d2d",
        "on-secondary-fixed": "#3b0900",
        "outline": "#747878",
        "outline-variant": "#c4c7c7",
        "primary-fixed-dim": "#c8c6c6",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1c1b1a",
        "secondary": "#974730",
        "on-tertiary-container": "#a49181",
        "surface-bright": "#fdf9f6",
        "secondary-container": "#fe987c",
        "on-primary-fixed": "#1b1c1c",
        "on-secondary-container": "#772e1a",
        "primary": "#181919",
        "surface-container-highest": "#e5e2df",
        "on-tertiary-fixed": "#24190e",
        "surface": "#fdf9f6",
        "on-primary-container": "#959494",
        "inverse-surface": "#31302f",
        "secondary-fixed-dim": "#ffb5a1",
        "on-primary-fixed-variant": "#474747",
        "primary-fixed": "#e4e2e1",
        "tertiary": "#21170b",
        "on-error-container": "#93000a",
        "surface-tint": "#5f5e5e"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "unit": "8px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Bodoni Moda"],
        "display-lg-mobile": ["Bodoni Moda"],
        "label-caps": ["Inter"],
        "headline-sm": ["Bodoni Moda"],
        "display-lg": ["Bodoni Moda"]
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
};
